[run]
name = "thor"
port = 8080
env = "dev"
version = "v1.0.1"

[app]
default_page_size = 10
max_page_size = 100
upload_save_path = "/files"
upload_server_url = "http://127.0.0.1/resource"
upload_file_max_size = 20 # MB

[log]
access_log = "./log/access.log"
error_log = "./log/error.log"
level = "DEBUG" # level: DEBUG, INFO, WARNING, ERROR, FATAL
max_size = 200  # 进行日志切割前，日志文件的最大大小（MB）
max_age = 30    # 保留旧日志文件的的最大天数
max_backups = 7 # 保留旧文件的最大天数
compress = true # 是否压缩/归档旧文件

# 作业平台数据库
[odb]
addr="root:rootroot@tcp(127.0.0.1:3306)/ordin?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai"
max_open_conns = 16
max_idle_conns = 4
debug = true

# 巡检平台数据库
[idb]
addr="root:rootroot@tcp(127.0.0.1:3306)/inspection?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai"
max_open_conns = 16
max_idle_conns = 4
debug = true

# 预警平台数据库
[rdb]
addr="root:rootroot@tcp(127.0.0.1:3306)/risk?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai"
max_open_conns = 16
max_idle_conns = 4
debug = true

[redis]
addr = "127.0.0.1:6379"
password = ""
db = 0
pool_size = 100

[auth]
jwt_expire = 8760
